02 1 crud subject
esemedo/scale_up_back pull request #11
Opened 2024-02-29 14:27 UTC by VictorSulivan

2024-02-29 15:02 UTC, Sambachpx requested changes
Il y a encore du code en commentaire, il faut le supprimer

2024-02-29 15:04 UTC, Sambachpx commented
Il y a plusieurs fois la déclaration `const prisma = new PrismaClient();` à voir si c'est possible de faire juste une déclaration globale

2024-02-29 15:06 UTC, Sambachpx commented
Pense à bien control S pour que le Prettier se mette en route afin d'uniformiser le style du code

2024-02-29 15:08 UTC, Sambachpx commented
Pour les prochaines fois pensent à bien mettre le bon naming pour les commits pour rappel : 

Pour les commits : 

feature: le nom de la feature (pour une nouvelle fonctionnalité)

fix: le nom de la correction de bug

2024-02-29 15:12 UTC, Sambachpx commented
il me semble que les fichiers de migrations ne doivent pas être push @supercrocman non ?

2024-02-29 15:24 UTC, supercrocman commented
> il me semble que les fichiers de migrations ne doivent pas être push @supercrocman non ?

ouep

2024-02-29 15:33 UTC, supercrocman requested changes

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +/*
pas nécessaire

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +/*
pas nécessaire

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +const prisma = new PrismaClient();
pas besoin de redéclarer le client prisma pleins de fois une fois suffit

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +  const categorys = await prisma.category.findMany();
categories

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +export const getTestCategory = (req: Request, res: Response) => {
pas besoin

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +export const getCategoryeBySubjectId = async (req: Request, res: Response) => {
Category

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +  res.json(updatedCategory);
il manque le status res.status(200).json()

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +export const getTestSubject = (req: Request, res: Response) => {
pas nécessaire

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  res.json(newSubject);
status

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +      categoryId
il faut vérifier que la catégorie existe

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  const updatedSubject = await prisma.subject.update({
manque de verifications

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  res.json(updatedSubject);
status

2024-02-29 15:33 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  res.json({ message: 'Subject deleted successfully' });
status

2024-02-29 15:33 UTC, supercrocman commented on src/prisma/migrations/20240228141125_test/migration.sql
a supprimer

2024-02-29 15:33 UTC, supercrocman commented on src/prisma/migrations/migration_lock.toml
a supprimer

2024-02-29 15:33 UTC, supercrocman commented on src/index.ts
> +app.use('/sub', subjectRoutes)
/api/category
/api/subject
pas /sub/subject

2024-02-29 15:33 UTC, supercrocman commented on src/routes/SubjectRoutes.ts
> +router.post('/subject', createSubject);
utiliser 'express-validator'

2024-02-29 15:38 UTC, VictorSulivan commented on src/controllers/SubjectController.ts
> +      categoryId
On ne permet de choisir que des categories existantes dans le front donc est ce bien nécessaire de vérifier aussi en back?

2024-02-29 15:43 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +      categoryId
![Capture d’écran 2024-02-29 à 16 42 59](https://github.com/scaleup-coding-factory-L2/scale_up_back/assets/33990741/2062329d-4516-416f-b739-bb6ae2cd8171)

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +export const getAllCategory = async (req: Request, res: Response) => {
getAllCategories

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +    res.status(500).json({ message: error.message });
Il faut éviter de renvoyer les messages d'erreurs non voulu / non maitrisé

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +export const createCategory = async (req: Request, res: Response) => {
il n'y as pas de verification pour savoir si la categorie n'existe pas déja ? ou c'est voulu ?

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +  const updatedCategory = await prisma.category.update({
il n'y as pas de vérification pour savoir si la categorie existe bien ? qu'est ce qui passe si la categorie n'existe pas ?

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +  await prisma.category.delete({
il n'y as pas de vérification pour savoir si la categorie existe bien ? qu'est ce qui passe si la categorie n'existe pas ?

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +const prisma = new PrismaClient();
pas besoin de redéclarer le client prisma pleins de fois une fois suffit

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +export const getAllSubject = async (req: Request, res: Response) => {
getAllSubjects

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +    res.status(500).json({ message: error.message });
Il faut éviter de renvoyer les messages d'erreurs non voulu / non maitrisé

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  const newSubject = await prisma.subject.create({
il n'y as pas de verification pour savoir si le subject n'existe pas déja ? ou c'est voulu ?

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +export const updateSubject = async (req: Request, res: Response) => {
il n'y as pas de vérification pour savoir si le subject existe bien ? qu'est ce qui passe si le subject n'existe pas ?

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  const updatedSubject = await prisma.subject.update({
il n'y as pas de verification pour savoir si le subject n'existe pas déja ? ou c'est voulu ?

2024-02-29 18:59 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  const { id } = req.params;
il n'y as pas de vérification pour savoir si le subject existe bien ? qu'est ce qui passe si le subject n'existe pas ?

2024-02-29 18:59 UTC, supercrocman commented on src/routes/CategoryRoutes.ts
> +router.get('/category', getAllCategory);
l'url vas être /api/category/category
alors qu'elle devrait être /api/category

2024-02-29 18:59 UTC, supercrocman commented on src/routes/SubjectRoutes.ts
> +router.get('/subject', getAllSubject);
l'url vas être /api/subject/subject
alors qu'elle devrait être /api/subject

2024-02-29 18:59 UTC, supercrocman commented on src/routes/CategoryRoutes.ts
> +router.post('/category', createCategory);
utiliser 'express-validator'

2024-03-01 09:15 UTC, xivsacha commented on src/routes/CategoryRoutes.ts
> +router.get('/category', getAllCategory);
Je ne peux pas resolve la conversation mais problème réglé ici

2024-03-01 09:21 UTC, Geuzivv commented on src/controllers/SubjectController.ts
> +      categoryId
En somme, la catégorie existe, vu que tu ne peux modifier une catégorie que si elle s'affiche sur le site, soit qu'elle existe, non ?

2024-03-01 09:26 UTC, xivsacha commented on src/controllers/CategoryController.ts
> +export const createCategory = async (req: Request, res: Response) => {
Actuellement, il n'y a pas de vérifications pour vérifier que l'utilisateur n'entre pas de doublons. Si vraiment nécessaire, on pourra la rajouter. Mais pour celle-ci, nous estimons qu'elle n'est pas particulièrement attendue

2024-03-01 09:27 UTC, xivsacha commented on src/controllers/CategoryController.ts
> +  const updatedCategory = await prisma.category.update({
La catégorie n'est modifiable uniquement si elle apparaît sur le Front ; en d'autres termes : qu'elle existe.

2024-03-01 09:29 UTC, xivsacha commented on src/controllers/SubjectController.ts
> +export const updateSubject = async (req: Request, res: Response) => {
A la manière des catégories, le subject n'est modifiable uniquement si il existe, étant affiché sur le front.

2024-03-01 09:30 UTC, xivsacha commented on src/controllers/SubjectController.ts
> +  const updatedSubject = await prisma.subject.update({
Pareil qu'avant sur les autres update (categories et subjects).

2024-03-01 09:30 UTC, xivsacha commented on src/controllers/SubjectController.ts
> +  const updatedSubject = await prisma.subject.update({
Pareil

2024-03-01 09:31 UTC, xivsacha commented on src/controllers/SubjectController.ts
> +  const newSubject = await prisma.subject.create({
Pareil

2024-03-01 09:32 UTC, xivsacha commented on src/controllers/SubjectController.ts
> +  const newSubject = await prisma.subject.create({
A la manière des categories, pour le moment, ce n'est pas nécessaire. Si vraiment nécessaire, ce sera modifié.

2024-03-01 10:27 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +export const getCategoryBySubjectId = async (req: Request, res: Response) => {
getCategoriesBySubjectId

2024-03-01 10:27 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +export const createCategory = async (req: Request, res: Response) => {
d'acc a voir avec françois

2024-03-01 10:27 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +  const updatedCategory = await prisma.category.update({
non

2024-03-01 10:27 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  const newSubject = await prisma.subject.create({
d'acc a voir avec François

2024-03-01 10:27 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +      categoryId
non le front et l'api son deux choses differentes. le front a besoin de l'api pour fonctionner. Mais l'api n'as pas besoin du front pour fonctionner elle est donc libre

2024-03-01 10:27 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +export const updateSubject = async (req: Request, res: Response) => {
non

2024-03-01 10:27 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  const updatedSubject = await prisma.subject.update({
non

2024-03-01 10:27 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  const updatedSubject = await prisma.subject.update({
a voir avec François

2024-03-01 10:27 UTC, supercrocman commented on src/prisma/migrations/20240228141125_test/migration.sql
a supprimer

2024-03-01 10:27 UTC, supercrocman commented on src/prisma/migrations/migration_lock.toml
a supprimer

2024-03-01 10:27 UTC, supercrocman commented on src/routes/SubjectRoutes.ts
> +router.delete('/subject/:id', deleteSubject);
supprimer les commentaires

2024-03-01 10:27 UTC, supercrocman commented on src/routes/SubjectRoutes.ts
> +router.get('/subject', getAllSubjects);
l'url sera /api/subject/subject: pas bon

2024-03-01 10:27 UTC, supercrocman commented on src/routes/SubjectRoutes.ts
> +  body('name').notEmpty().withMessage('Name is required'),
rajouter une limite de taille

2024-03-01 10:27 UTC, supercrocman commented on src/routes/CategoryRoutes.ts
> +router.delete('/category/:id', deleteCategory);
l'url sera /api/category/category: pas bon

2024-03-01 10:34 UTC, xivsacha commented on src/routes/SubjectRoutes.ts
> +router.delete('/subject/:id', deleteSubject);
C'est la version fonctionnelle que Mattéo souhaitait garder de côté pour le moment, t'es sûr ?

2024-03-02 15:28 UTC, supercrocman commented on yarn.lock
il faut le supprimer on utilise npm pas yarn

2024-03-02 15:28 UTC, supercrocman commented on src/routes/CategoryRoutes.ts
> +router.put('/category/:id',[
l'url sera /api/category/category: pas bon

2024-03-04 12:50 UTC, supercrocman requested changes

2024-03-04 12:50 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +
il faudrait rajouter const existingCategory = await prisma.category.findFirst({
    where: {
      name: name,
    },
  });

  if (existingCategory) {
    return res.status(404).json({ error: `La catégorie à créer existe déjà` });
  }

2024-03-04 12:50 UTC, supercrocman commented on src/routes/CategoryRoutes.ts
> +router.put('/category/:id',[
le mieux est de mettre router.get('/', getAllCategories);
et dans src index.ts app.use('/api/category', categoryRoutes)

2024-03-04 12:50 UTC, supercrocman commented on src/routes/SubjectRoutes.ts
> +router.get('/subject', getAllSubjects);
le mieux est de mettre router.get('/', getAllSubjects);
et dans src index.ts app.use('/api/subject', subjectRoutes)

2024-03-04 12:50 UTC, supercrocman commented on yarn.lock
a Supprimer on utilise pas yarn mais npm

2024-03-04 12:50 UTC, supercrocman commented on yarn.lock
up

2024-03-04 12:50 UTC, supercrocman commented on yarn.lock
a suppr on utilise npm

2024-03-11 18:20 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +
if (!existingCategory) {
    return res.status(404).json({ error: `La category que vous voulez utilisé pour créer la matière/module n'existe pas.` });
  }

2024-03-11 18:20 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +    return res.status(404).json({ error: `La category que vous voulez utilisé pour créer la matière/module n'existe pas.` });
a déplacer

2024-03-11 18:20 UTC, supercrocman commented on src/controllers/SubjectController.ts
> +  if (!existingSubject) {
A deplacer

2024-03-12 14:36 UTC, supercrocman approved these changes

2024-03-13 13:02 UTC, supercrocman commented on src/controllers/CategoryController.ts
> +    const category = await prisma.category.findMany({
findMany n'est pas bon il y a d'autres fonctions plus adapté, il renvoi plusieurs éléments

2024-03-17 16:13 UTC, Sambachpx commented on src/routes/CategoryRoutes.ts
> +    body('name').isLength({ min: 5, max: 20 }).withMessage('La longueur doit être entre 5 et 20 caractères pour le name de la catégorie'),
Les vérifications de longueur du name ne fonctionnent pas (et aucun message dans la console), je peux créer des catégories avec 1 caractère tout comme 600, je ne sais pas si c'est aussi possible de vérifier le type de ce qu'on entre là, je peux mettre des number, il faudra voir ce point-là avec @supercrocman 
<img width="1008" alt="Screenshot 2024-03-17 at 17 08 29" src="https://github.com/scaleup-coding-factory-L2/scale_up_back/assets/113524274/6dcde3d0-62cd-494d-bd46-68599490f6b6">
![Uploading Screenshot 2024-03-17 at 17.08.40.png…]()

2024-03-17 16:18 UTC, Sambachpx commented on src/controllers/CategoryController.ts
> +  } catch (error) {
je serais d'avis pour que dans les catchs il y ait aussi l'erreur pour debug + facilement

2024-03-17 16:20 UTC, Sambachpx requested changes
Coup de prettier à faire aussi si possible

2024-03-17 16:30 UTC, Sambachpx commented
Pense à resolve les conversations aussi quand les soucis sont réglés 😉

2024-03-21 16:32 UTC, Sambachpx approved these changes

2024-03-21 20:46 UTC, merged